# version: '3.8'

services:
  backend:
    image: node:18
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    command: >
      sh -c "npm install && npm run dev"

  python-ml:
    image: python:3.11
    container_name: python-ml
    working_dir: /ml
    volumes:
      - ./ml:/ml
    command: tail -f /dev/null

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: estoque
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
